mode: inference

data:
  inference_input:
    dir: ./data/mmv_im2im/denoise/test/im   #ADD-YOURS
    data_type: tif
    reader_params:
      dimension_order_out: "ZYX"
      C: 0
      T: 0
  inference_output:
    path: ./data/mmv_im2im/denoise/test/pred  #ADD-YOURS
  preprocess:   
    - module_name: monai.transforms
      func_name: AddChannel
      
    - module_name: monai.transforms
      func_name: ScaleIntensityRangePercentiles
      params:
        lower: 3  # between 1 and 3
        upper: 99.9  # between 99.5 and 99.9
        b_min: 0
        b_max: 1

model:
  framework: FCN
  net:
    module_name: monai.networks.nets
    func_name: UNet
    params:
      spatial_dims: 3
      in_channels: 1
      out_channels: 1
      channels: [32, 64, 128, 256]
      strides: [2, 2, 2]
      num_res_units: 3
      norm: "BATCH"
  checkpoint: ./model/mmv_im2im/denoising_3d.ckpt  #ADD-YOURS
  model_extra:
    sliding_window_params:
      roi_size: [32, 128, 128] #origin [32, 512, 512]
      sw_batch_size: 4
      overlap: 0.2
      mode: "constant"
trainer:
  params:
    gpus: 1
    precision: 16
