mode: inference

data:
  category: "pair"
  data_path: "/mnt/data/ISAS.DE/yu.zhou/Yu/project/mmv_im2im_domain_adaptation/data/labelfree_3d"   #calibration data
  dataloader:
    train:
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 4
  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM", "GT"]
        dimension_order_out: "ZYX"
        C: 0
        T: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["IM", "GT"]
    - module_name: mmv_im2im.preprocessing.transforms
      func_name: norm_around_center
      params:
        keys: ["IM","GT"]
        min_z: 32
    #- module_name: monai.transforms
    #  func_name: RandSpatialCropSamplesd
    #  params:
    #    keys: ["IM", "GT"]
    #    random_size: False
    #    num_samples: 1
    #    roi_size: [48, 512, 912]    

model:
  framework: FCN 
  net:
    module_name: mmv_im2im.models.nets.fnet_nn_3d
    func_name: Net
    params:
      depth: 4
      mult_chan: 32
      in_channels: 1
      out_channels: 1
  criterion:
    module_name: torch.nn
    func_name: MSELoss
    params:
      reduction: 'mean'
  optimizer:
    module_name: torch.optim
    func_name: Adam  # AdamW
    params:
      lr: 0.001
      weight_decay: 0.0005
  scheduler:
    module_name: torch.optim.lr_scheduler
    func_name: ExponentialLR
    params:
      gamma: 0.98
  checkpoint: "model/mmv_im2im/labelfree_3d.ckpt"
  model_extra:
    sliding_window_params:
      roi_size: [32, 128, 128]
      sw_batch_size: 4
      overlap: 0.2
      mode: "gaussian"

trainer:
  verbose: True
  params:
    gpus: 1
    precision: 16
    max_epochs: 1000

