model:
  model_name: mmv_im2im #currently, could be mmv_im2im, cellpose, omnipose
  mmv_im2im:
    task: labelfree
    model_type: FCN
    config_path: "configs/mmv_im2im/labelfree_3d.yaml"
  cellpose:
    task: instance_seg
    model_type: cyto2
    config_path: "configs/cellpose/instanceseg_2d.yaml"
  omnipose:
    task: instance_seg
    model_type: cyto2
    config_path: "configs/omnipose/instanceseg_2d.yaml"
data:
  data_path: "/mnt/data/ISAS.DE/yu.zhou/Yu/project/datasets/labelfree_3d"
  input_size: [1,1,32,128,128] #should be the same in labelfree_3d_deploy.yaml
  dynamic_batch: [1,4,8] # min, opt, max
  io:
    input_names: ['input']
    output_names: ['output']
quantization:
  toolbox: mqbench #ppq or mqbench
  backend: tensorrt # tensorrt or openvino
  run_mode: int8 #int8 or fp32
  extra_qconfig_dict: 
    w_observer: EMAQuantileObserver
    a_observer: EMAQuantileObserver
    w_fakequantize: LearnableFakeQuantize
    a_fakequantize: LearnableFakeQuantize
    w_qscheme: 
      bit: 8
      symmetry: True
      per_channel: False
      pot_scale: False
    a_qscheme: 
      bit: 8
      symmetry: True
      per_channel: False
      pot_scale: False

